// src/app/terms/page.tsx
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export const metadata = {
  title: "Terms of Service — hitd.ai",
  description: "Terms of Service for hitd.ai.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-50 font-sans">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-slate-900 transition-colors mb-10"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to hitd.ai
        </Link>

        <div className="bg-white rounded-3xl border border-slate-200 shadow-sm p-8 md:p-12">
          <p className="text-[10px] font-bold text-blue-500 uppercase tracking-widest mb-3">Legal</p>
          <h1 className="text-3xl md:text-4xl font-[800] text-slate-900 tracking-tight mb-2">Terms of Service</h1>
          <p className="text-sm text-slate-400 font-medium mb-10">Effective date: April 19, 2026</p>

          <div className="space-y-8 text-[14px] leading-relaxed text-slate-600">

            <p>
              By accessing or using hitd.ai, you agree to be bound by these Terms of Service. If you do not agree,
              do not use the service.
            </p>

            <section>
              <h2 className="text-[16px] font-[800] text-slate-900 mb-3">1. Description of service</h2>
              <p>
                hitd.ai provides AI-powered analysis of advertising creatives and copy. All results, scores, and
                recommendations generated by the service are informational only. We do not guarantee that your ads
                will be approved by Meta or any other advertising platform, nor do we guarantee any specific outcome
                in terms of conversion rate, click-through rate, or ad performance. Results may vary based on factors
                outside our control, including changes to platform policies.
              </p>
            </section>

            <section>
              <h2 className="text-[16px] font-[800] text-slate-900 mb-3">2. Payments and refunds</h2>
              <p>
                All purchases are final. We do not offer refunds for any reason, including but not limited to unused
                analysis credits, dissatisfaction with results, or changes to the service. By completing a purchase
                you acknowledge and accept this no-refund policy.
              </p>
            </section>

            <section>
              <h2 className="text-[16px] font-[800] text-slate-900 mb-3">3. Acceptable use</h2>
              <p>
                You agree not to use hitd.ai to analyze content that is illegal, defamatory, discriminatory, or that
                promotes violence or hate. You may not use the service to intentionally circumvent advertising platform
                policies or to facilitate deceptive advertising practices. We reserve the right to suspend or terminate
                accounts that violate this section without refund.
              </p>
            </section>

            <section>
              <h2 className="text-[16px] font-[800] text-slate-900 mb-3">4. Your content</h2>
              <p>
                You retain full ownership of all content you upload to hitd.ai. By uploading content, you grant us a
                limited, non-exclusive license to process it solely for the purpose of providing the service. We do
                not use your content for any other purpose.
              </p>
            </section>

            <section>
              <h2 className="text-[16px] font-[800] text-slate-900 mb-3">5. Limitation of liability</h2>
              <p>
                hitd.ai is provided &quot;as is&quot; without warranties of any kind. To the maximum extent permitted by law,
                hitd.ai LLC shall not be liable for any indirect, incidental, special, or consequential damages
                arising from your use of the service, including but not limited to account suspensions by Meta or
                other platforms, loss of revenue, or loss of data. Our total liability to you for any claim shall not
                exceed the amount you paid us in the 30 days prior to the claim.
              </p>
            </section>

            <section>
              <h2 className="text-[16px] font-[800] text-slate-900 mb-3">6. Intellectual property</h2>
              <p>
                All content, branding, and technology on hitd.ai is owned by hitd.ai LLC and may not be reproduced
                without written permission.
              </p>
            </section>

            <section>
              <h2 className="text-[16px] font-[800] text-slate-900 mb-3">7. Governing law</h2>
              <p>
                These Terms are governed by the laws of the State of Florida, United States. Any disputes shall be
                resolved in the courts of Miami-Dade County, Florida.
              </p>
            </section>

            <section>
              <h2 className="text-[16px] font-[800] text-slate-900 mb-3">8. Changes to these terms</h2>
              <p>
                We may update these Terms at any time. Continued use of the service after changes constitutes
                acceptance.
              </p>
            </section>

            <section>
              <h2 className="text-[16px] font-[800] text-slate-900 mb-3">9. Contact</h2>
              <p>
                For any questions regarding these Terms, contact us at{" "}
                <a href="mailto:hello@hitd.ai" className="text-blue-600 font-semibold hover:underline">
                  hello@hitd.ai
                </a>.
              </p>
            </section>

          </div>
        </div>
      </div>
    </div>
  );
}
